name: student_job_finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Network
  dio: ^5.3.2
  http: ^1.1.0
  
  # State Management
  flutter_bloc: ^9.1.1
  bloc: ^9.0.1
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Navigation
  go_router: ^14.2.7
  
  # Utils
  uuid: ^4.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  responsive_builder: ^0.7.0
  
  # Animations
  rive: ^0.13.1
  
  # Logging
  logger: ^2.0.2+10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
